name: 'Detect PII'

on: push
jobs:
  detect-pii:
    runs-on: ubuntu-latest
    steps:
      - uses: rob-derosa/pii-detector@v1
        name: "Run PII detector"
        with:
          azure-cognitive-subscription-key: ${{ secrets.AZURE_COGNITIVE_SUBSCRIPTION_KEY }}
          azure-cognitive-endpoint: ${{ secrets.AZURE_COGNITIVE_ENDPOINT }}
          categories: "email|ip|phone number"
          label-text: "PII Detected!!"
          github-token: ${{ secrets.GITHUB_TOKEN }}

####
